

/*const promise=new Promise((resolve,reject)=>{
    setTimeout(()=>{resolve('something was resolved')
        reject('something went wrong')
        
    },2500)
})
promise.then((data)=>{
console.log(data);
}).catch((error)=>{
    console.log('error:',error)
})*/